### ISSUE TITLE
Windows Defender marks v1.0.2 as Trojan:Win32/Azden.A!cl

### ISSUE THREAD

**Issue by Razunter** [siegrest/Exiled-Presence#6]
Title

**Comment by siegrest** [comment]
This was mentioned in the [reddit release thread](https://www.reddit.com/r/pathofexile/comments/ayqpwn/release_exiled_presence_discord_rich_presence/) as well. As of right now I have no idea why or what is causing it. Nothing like getting punched in the face by windows for developing in C#.

**Comment by Razunter** [comment]
Just send this to MS for review, I guess...
https://www.microsoft.com/en-us/wdsi/filesubmission

**Comment by siegrest** [comment]
Done. I really hope I don't have to repeat this for every single release.

**Comment by siegrest** [comment]
Microsoft has approved the submission and removed the detection. Let me know if anything else comes up.

**Comment by Razunter** [comment]
Windows Defender updated, no issues now.

**Comment by Razunter** [comment]
@siegrest same issue with v1.0.3 😥

**Comment by siegrest** [comment]
Submitted the new release, Microsoft approved it.

```
We have removed the detection. Please follow the steps below to clear cached detection and obtain the latest malware definitions.

1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender 
2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
3. 3. Run “MpCmdRun.exe -SignatureUpdate” 
```

It's a bit tedious that I have to do this for every single release. Really wish I could get my hands on some certs but that's the life of a 3rd party tooldev.
